AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template for creating an Amazon SageMaker notebook instance with FSX for NetApp ONTAP file system'

Parameters:
  NotebookInstanceName:
    AllowedPattern: '[A-Za-z0-9-]{1,63}'
    ConstraintDescription: Maximum of 63 alphanumeric characters. Can include hyphens
      (-), but not spaces. Must be unique within your account in an AWS Region.
    Description: SageMaker Notebook Instance Name
    MaxLength: '63'
    MinLength: '1'
    Type: String
    Default: 'FSXNotebookInstance'
  NotebookInstanceType:
    AllowedValues:
      - ml.t2.medium
      - ml.t2.large
      - ml.t2.xlarge
      - ml.t2.2xlarge
      - ml.t3.medium
      - ml.t3.large
      - ml.t3.xlarge
      - ml.t3.2xlarge
      - ml.m4.xlarge
      - ml.m4.2xlarge
      - ml.m4.4xlarge
      - ml.m4.10xlarge
      - ml.m4.16xlarge
      - ml.m5.large
      - ml.m5.xlarge
      - ml.m5.2xlarge
      - ml.m5.4xlarge
      - ml.m5.12xlarge
      - ml.m5.24xlarge
      - ml.c4.xlarge
      - ml.c4.2xlarge
      - ml.c4.4xlarge
      - ml.c4.8xlarge
      - ml.c5.xlarge
      - ml.c5.2xlarge
      - ml.c5.4xlarge
      - ml.c5.9xlarge
      - ml.c5.18xlarge
      - ml.c5d.xlarge
      - ml.c5d.2xlarge
      - ml.c5d.4xlarge
      - ml.c5d.9xlarge
      - ml.c5d.18xlarge
      - ml.p2.xlarge
      - ml.p2.8xlarge
      - ml.p2.16xlarge
      - ml.p3.2xlarge
      - ml.p3.8xlarge
      - ml.p3.16xlarge
    ConstraintDescription: Must select a valid notebook instance type.
    Default: ml.t2.medium
    Description: Select Instance type for the SageMaker Notebook Instance
    Type: String
  SubnetId:
    Description: SubnetId in your Virtual Private Cloud (VPC)
    Type: AWS::EC2::Subnet::Id
  SecurityGroupIds:
    Description: The VPC security group IDs, in the form sg-xxxxxxxx. The security groups must be for the same VPC as specified in the subnet.
    Type: List<AWS::EC2::SecurityGroup::Id>

Resources:
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: !Ref NotebookInstanceType
      NotebookInstanceName: !Ref NotebookInstanceName
      RoleArn: !GetAtt ExecutionRole.Arn
      SubnetId: !Ref SubnetId
      SecurityGroupIds: !Ref SecurityGroupIds
      LifecycleConfigName: !GetAtt LifecycleConfig.NotebookInstanceLifecycleConfigName

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess

  LifecycleConfig:
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties:
      OnStart:
        - Content:
            Fn::Base64: !Sub |
              #!/bin/bash
              set -e
              # OVERVIEW
              # This script mounts FSX for NetApp ONTAP file system on a SageMaker notebook instance
              #
              # Note that this script will fail if the file system mount target is not in the same availability zone as this notebook instance.
              # 
              # You can optionally change the local directory (mount point) by changing the value of the MOUNT_POINT variable below.
              # By default, we mount the file system on /mnt/efs.
              
              MOUNT_POINT=/mnt/fsx

              # Install NFS client
              yum install -y nfs-utils

              # Get region of this EC2 instance
              REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
              echo $REGION

              # Create mount directory
              mkdir -p ${MOUNT_POINT}

              # Mount FSX file system
              # Note: Update the mount target DNS name below to match your file system
              mount -t nfs -o nfsvers=3 management-ip.fsx-file-system-id.fsx.region.amazonaws.com:/vol1 ${MOUNT_POINT}

              # Validate that the file system was mounted successfully
              df -h ${MOUNT_POINT}

Outputs:
  NotebookInstanceName:
    Value: !Ref NotebookInstance
  NotebookInstanceId:
    Value: !Ref NotebookInstance
